Name(7)
=======


NAME
----
fty-common - Overview of Provides common tools for agents


SYNOPSIS
--------

Project fty-common aims to ... (short marketing pitch)

It delivers several programs with their respective man pages:

and public classes in a shared library:
 fty_common_log_fty_log.3 fty_common_common_fty_commons.3 fty_common_web_helpers.3 fty_common_web_sasl.3 fty_common_web_tokens.3 fty_common_web_utils_web.3 fty_common_common_str_defs.3 fty_common_common_filesystem.3 fty_common_db_dbpath.3

Generally you can compile and link against it like this:
----
#include <fty_common.h>

cc ['flags'] 'files' -lfty_common ['libraries']
----


DESCRIPTION
-----------

This is a skeleton document created by zproject, which will not be
regenerated automatically (by Makefiles nor project.xml re-parsing).
You should add hand-written text here to detail whatever applies to
Linux standard manpage Section 7 (note that other OSes may follow
a different standard with similar concepts, and extend the recipes
to package this document into a different section number):

----
7 Overview, conventions, and miscellaneous :
    Overviews or descriptions of various topics, conventions
    and protocols, character set standards, the standard
    filesystem layout, and miscellaneous other things.
----

Classes
~~~~~~~

Something for developers to consider. Note there are separate man
pages generated for public classes during build with contents taken
from source code comments.

